### ISSUE TITLE
ImportError in nebula_carina.ngql.schema.space of create_space (most likely due to a circular import)

### ISSUE THREAD

**Issue by toshihiro1995** [nebula-contrib/nebula-carina#13]
Hi.

The sample code in the README didn't work.

```python
from nebula_carina.ngql.schema.space import create_space, show_spaces, VidTypeEnum

main_space_name = "main"

if main_space_name not in show_spaces():
    create_space(main_space_name, (VidTypeEnum.FIXED_STRING, 20))
```

It's because a circular import.
It is imported in: https://github.com/nebula-contrib/nebula-carina/blob/main/nebula_carina/ngql/connection/connection.py#L107, which is also used in nebula_carina.ngql.schema.space.

Here is error messages:
```bash
Python 3.10.5 (main, May  1 2023, 20:40:12) [GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from nebula_carina.ngql.schema.space import create_space
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "hoge/.venv/lib/python3.10/site-packages/nebula_carina/ngql/schema/space.py", line 1, in <module>
    from nebula_carina.ngql.connection.connection import run_ngql, LocalSession
  File "hoge/nebula-mcat/.venv/lib/python3.10/site-packages/nebula_carina/ngql/connection/connection.py", line 107, in <module>
    from nebula_carina.ngql.schema.space import create_space, show_spaces  # noqa
ImportError: cannot import name 'create_space' from partially initialized module 'nebula_carina.ngql.schema.space' (most likely due to a circular import) (hoge/nebula-mcat/.venv/lib/python3.10/site-packages/nebula_carina/ngql/schema/space.py)
```

**Comment by SwordElucidator** [comment]
Thank you for reporting. Would be nice if you can submit a PR for this issue, or I'd like to fix it in the next few days.
